# Generated by Django 3.2 on 2022-04-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=250, verbose_name='Nombre del usuario')),
                ('first_surname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellido Paterno')),
                ('second_surname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellido Materno')),
                ('cap_num', models.PositiveBigIntegerField(verbose_name='No. de Colegiatura')),
                ('identity', models.CharField(blank=True, help_text='DNI o RUC', max_length=11, verbose_name='Documento de Identidad')),
                ('person_type', models.CharField(choices=[('N', 'NATURAL'), ('J', 'JURÍDICA')], default='N', help_text='Tipo de Persona', max_length=1, verbose_name='Tipo de Persona')),
                ('profession', models.CharField(blank=True, choices=[('A', 'ARQUITECTO'), ('I', 'INGENIERO'), ('O', 'OTRO')], help_text='Profesión', max_length=1, verbose_name='Profesión')),
                ('mobile', models.CharField(blank=True, help_text='Número de Teléfono Celular', max_length=12, verbose_name='Celular')),
                ('phone', models.CharField(blank=True, help_text='Número de Teléfono Fijo o de Oficina', max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Correo Electrónico', max_length=50, verbose_name='Email')),
                ('secret_code', models.PositiveIntegerField(blank=True, help_text='Código Secreto de Arquitecto', null=True, verbose_name='Código Secreto de Arquitecto')),
                ('address', models.CharField(blank=True, help_text='Dirección', max_length=200, verbose_name='Dirección')),
                ('price_month', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('price_year', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('V', 'VISA'), ('M', 'MASTERCARD'), ('E', 'EFECTIVO')], default='V', max_length=10, null=True)),
                ('membership_type', models.CharField(blank=True, choices=[('PNA', 'Plan no Agremiado'), ('PLPA', 'Pago en Linea - Plan Agremiado'), ('PLPPA', 'Pago en Linea - Plan Premium Agremiado'), ('PLPP', 'Pago en Linea - Plan Profesional'), ('PPPA', 'Pagos Presenciales - Plan Agremiado'), ('PPPPA', 'Pagos Presenciales - Plan Premium Agremiado'), ('PPPP', 'Pagos Presenciales - Plan Profesional')], default='PLPA', max_length=30, null=True)),
                ('is_enabled', models.BooleanField(default=False, verbose_name='¿Esta habilitado?')),
                ('penalty_fee', models.BooleanField(default=False, verbose_name='¿Tiene multas?')),
                ('has_tutition', models.BooleanField(default=False, verbose_name='¿Es colegiado?')),
                ('is_client', models.BooleanField(default=False, verbose_name='¿Es cliente?')),
                ('date_enrollment', models.DateTimeField(blank=True, null=True, verbose_name='fecha de inscripcion')),
                ('date_expired', models.DateTimeField(blank=True, null=True, verbose_name='fecha de caducidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Beneficios de las membresias')),
            ],
            options={
                'verbose_name_plural': 'Beneficios de las Membresías',
            },
        ),
        migrations.CreateModel(
            name='MembershipConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Condiciones de las membresias')),
            ],
            options={
                'verbose_name_plural': 'Condiciones de las Membresías',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Plan')),
                ('membership_type', models.CharField(choices=[('PNA', 'Plan no Agremiado'), ('PLPA', 'Pago en Linea - Plan Agremiado'), ('PLPPA', 'Pago en Linea - Plan Premium Agremiado'), ('PLPP', 'Pago en Linea - Plan Profesional'), ('PPPA', 'Pagos Presenciales - Plan Agremiado'), ('PPPPA', 'Pagos Presenciales - Plan Premium Agremiado'), ('PPPP', 'Pagos Presenciales - Plan Profesional')], default='PLPA', max_length=30)),
                ('price_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_quarterly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Trimestral')),
                ('price_year', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('benefits', models.ManyToManyField(to='membership.MembershipBenefits')),
                ('conditions', models.ManyToManyField(blank=True, to='membership.MembershipConditions')),
            ],
            options={
                'verbose_name_plural': 'Clases de Membresías',
            },
        ),
    ]
