# Generated by Django 3.2 on 2022-03-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=250, verbose_name='Nombre del usuario')),
                ('cap_num', models.PositiveBigIntegerField(verbose_name='No. de Colegiatura')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='¿Esta habilitado?')),
                ('penalty_fee', models.BooleanField(default=False, verbose_name='¿Tiene multas?')),
                ('has_tutition', models.BooleanField(default=False, verbose_name='¿Es colegiado?')),
                ('identity', models.CharField(blank=True, help_text='DNI o RUC', max_length=11, verbose_name='Documento de Identidad')),
                ('date_enrollment', models.DateField(blank=True, null=True, verbose_name='fecha de inscripcion')),
                ('date_expired', models.DateField(blank=True, null=True, verbose_name='fecha de caducidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Beneficios de las membresia')),
            ],
            options={
                'verbose_name_plural': 'Beneficios de las Membresías',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('PNA', 'Plan no Agremiado'), ('PLPA', 'Pago en Linea - Plan Agremiado'), ('PLPPA', 'Pago en Linea - Plan Premium Agremiado'), ('PLPP', 'Pago en Linea - Plan Profesional'), ('PPPA', 'Pagos Presenciales - Plan Agremiado'), ('PPPPA', 'Pagos Presenciales - Plan Premium Agremiado'), ('PPPP', 'Pagos Presenciales - Plan Profesional')], default='PLPA', max_length=30)),
                ('price_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_year', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('benefits', models.ManyToManyField(to='membership.MembershipBenefits')),
            ],
            options={
                'verbose_name_plural': 'Clases de Membresías',
            },
        ),
    ]
