# Generated by Django 3.2 on 2022-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimember',
            name='date_enrollment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de inscripcion'),
        ),
        migrations.AlterField(
            model_name='apimember',
            name='date_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de caducidad'),
        ),
    ]
