# Generated by Django 3.2 on 2022-03-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Condiciones de las membresias')),
            ],
            options={
                'verbose_name_plural': 'Condiciones de las Membresías',
            },
        ),
        migrations.AlterField(
            model_name='membershipbenefits',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Beneficios de las membresias'),
        ),
        migrations.AddField(
            model_name='membership',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='membership.MembershipConditions'),
        ),
    ]
