# Generated by Django 3.2 on 2022-03-04 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimember',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='apimember',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, help_text='Correo Electrónico', max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apimember',
            name='first_surname',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='apimember',
            name='mobile',
            field=models.CharField(blank=True, help_text='Número de Teléfono Celular', max_length=12, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='apimember',
            name='person_type',
            field=models.CharField(choices=[('N', 'NATURAL'), ('J', 'JURÍDICA')], default='N', help_text='Tipo de Persona', max_length=1, verbose_name='Tipo de Persona'),
        ),
        migrations.AddField(
            model_name='apimember',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de Teléfono Fijo o de Oficina', max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='apimember',
            name='profession',
            field=models.CharField(blank=True, choices=[('A', 'ARQUITECTO'), ('I', 'INGENIERO'), ('O', 'OTRO')], help_text='Profesión', max_length=1, verbose_name='Profesión'),
        ),
        migrations.AddField(
            model_name='apimember',
            name='second_surname',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='apimember',
            name='secret_code',
            field=models.PositiveIntegerField(blank=True, help_text='Código Secreto de Arquitecto', null=True, verbose_name='Código Secreto de Arquitecto'),
        ),
    ]
