# Generated by Django 3.2 on 2022-04-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimember',
            name='foreign_card',
            field=models.CharField(blank=True, help_text='Documento de Extranjería', max_length=11, verbose_name='Documento de Extranjería'),
        ),
    ]
