# Generated by Django 3.2 on 2022-03-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_price_quarterly'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimember',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='¿Es cliente?'),
        ),
    ]
