# Generated by Django 3.2 on 2022-04-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20220412_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Plan'),
        ),
    ]
