# Generated by Django 3.2 on 2022-03-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20220304_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimember',
            name='price_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apimember',
            name='price_year',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
