# Generated by Django 3.2 on 2022-03-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20220307_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimember',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('PNA', 'Plan no Agremiado'), ('PLPA', 'Pago en Linea - Plan Agremiado'), ('PLPPA', 'Pago en Linea - Plan Premium Agremiado'), ('PLPP', 'Pago en Linea - Plan Profesional'), ('PPPA', 'Pagos Presenciales - Plan Agremiado'), ('PPPPA', 'Pagos Presenciales - Plan Premium Agremiado'), ('PPPP', 'Pagos Presenciales - Plan Profesional')], default='PLPA', max_length=30, null=True),
        ),
    ]
