# Generated by Django 3.2 on 2022-05-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_apimember_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimember',
            name='foreign_card',
        ),
    ]
