# Generated by Django 3.2 on 2022-03-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_apimember_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimember',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('V', 'VISA'), ('M', 'MASTERCARD'), ('E', 'EFECTIVO')], default='V', max_length=10, null=True),
        ),
    ]
