# Generated by Django 3.2 on 2022-02-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_normativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='date_normativa',
            table='busqueda_normativa',
        ),
    ]
