# Generated by Django 3.2 on 2022-04-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='fecha_publicacioncacion',
            new_name='fecha_publicacion',
        ),
    ]
