# Generated by Django 3.2 on 2022-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_auto_20220426_2240'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Titulo del video')),
                ('norma', models.CharField(max_length=200, verbose_name='Norma')),
                ('propiedad', models.CharField(choices=[('PU', 'Publico'), ('PR', 'Privado')], default='PU', max_length=2, verbose_name='Propiedad Intelectual')),
                ('embed', models.TextField(verbose_name='Embed')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('caratula', models.FileField(blank=True, null=True, upload_to='cursos_caratulas', verbose_name='Caratula')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
