# Generated by Django 3.2 on 2022-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='embed',
            field=models.TextField(),
        ),
    ]
