# Generated by Django 3.2 on 2022-04-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20220406_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='caratula',
            field=models.FileField(null=True, upload_to='caratulas', verbose_name='Caratula'),
        ),
    ]
