# Generated by Django 3.2 on 2022-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20220427_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
