# Generated by Django 3.2 on 2022-04-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursos_caratula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='created',
        ),
        migrations.AddField(
            model_name='cursos',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
