# Generated by Django 3.2 on 2022-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20220407_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='caratula',
            field=models.FileField(blank=True, null=True, upload_to='caratulas', verbose_name='Caratula'),
        ),
    ]
