# Generated by Django 3.2 on 2022-03-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(help_text='Nombre de Categoria', max_length=200, verbose_name='Nombre de la Categoria')),
                ('order', models.CharField(blank=True, max_length=10)),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name_plural': 'Tipo de Uso',
            },
        ),
        migrations.CreateModel(
            name='Register_Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma', models.CharField(max_length=200, verbose_name='Norma')),
                ('name_denom', models.TextField(verbose_name='Denominacion')),
                ('base_legal', models.CharField(max_length=200, verbose_name='Base Legal')),
                ('fecha_publi', models.DateField(verbose_name='Publicacion')),
                ('document', models.FileField(null=True, upload_to='Document_normativa', verbose_name='Documentos')),
                ('es_foro', models.BooleanField(default=False, verbose_name='Es un foro')),
                ('es_vigente', models.BooleanField(default=False, verbose_name='Esta vigente')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name_plural': 'Normativas',
                'db_table': 'register_normativa',
            },
        ),
        migrations.CreateModel(
            name='Subcategories_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(help_text='Nombre de sub Categoria', max_length=200, verbose_name='sub Categoria')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('order', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name_plural': 'Subtipo De Normativa',
            },
        ),
        migrations.CreateModel(
            name='Register_Palabraclave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre Palabra Clave')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('normativas', models.ManyToManyField(blank=True, related_name='keywords', to='normas.Register_Normativa', verbose_name='Normativa')),
            ],
            options={
                'verbose_name_plural': 'Palabras Clave',
                'db_table': 'register_palabclave',
            },
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='tipo_norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.subcategories_normas', verbose_name='Tipo de Norma'),
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='tipo_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.areas_normas', verbose_name='Tipo Uso'),
        ),
        migrations.CreateModel(
            name='Policies_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo de Consulta', max_length=200, verbose_name='Titulo de Consulta')),
                ('message', models.TextField(help_text='Respuesta', verbose_name='Respuesta')),
                ('validity_date_start', models.DateField(help_text='Fecha Inicio', verbose_name='Fecha Inicio')),
                ('validity_date_finish', models.DateField(help_text='Fecha Fin', verbose_name='Fecha Fin')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('tipo_uso', models.ManyToManyField(blank=True, related_name='preguntas', to='normas.Areas_Normas', verbose_name='Tipo de uso')),
            ],
            options={
                'verbose_name_plural': 'Preguntas Frecuentes',
            },
        ),
    ]
