# Generated by Django 3.2 on 2022-03-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de Categoria', max_length=200, verbose_name='Nombre de la Categoria')),
                ('order', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name_plural': 'Tipo de Uso',
            },
        ),
        migrations.CreateModel(
            name='Estado_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Estado de norma')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name_plural': 'Estado de Norma',
            },
        ),
        migrations.CreateModel(
            name='Register_Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma', models.CharField(max_length=200, verbose_name='Norma')),
                ('name_denom', models.TextField(verbose_name='Denominacion')),
                ('base_legal', models.CharField(max_length=200, verbose_name='Base Legal')),
                ('fecha_publi', models.DateField(verbose_name='Publicacion')),
                ('document', models.FileField(null=True, upload_to='Document_normativa', verbose_name='Documentos')),
                ('propiedad', models.CharField(choices=[('PU', 'Publico'), ('PI', 'Propiedad Intelectual')], default='PU', max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('articulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Articulo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.estado_normas', verbose_name='Estado de la Norma')),
            ],
            options={
                'verbose_name_plural': 'Normativas',
                'db_table': 'register_normativa',
            },
        ),
        migrations.CreateModel(
            name='Universo_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de universo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name_plural': 'Topico Principal de Norma',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de Tipo de norma', max_length=200, verbose_name='Tipo norma')),
                ('order', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('universo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.universo_normas', verbose_name='Universo Norma')),
            ],
            options={
                'verbose_name_plural': 'Tipo de Norma',
            },
        ),
        migrations.CreateModel(
            name='Subtipo_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de subtipo')),
                ('order', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('tipo_uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.areas_normas', verbose_name='Tipo Uso')),
            ],
            options={
                'verbose_name_plural': 'Subtipo de Uso',
            },
        ),
        migrations.CreateModel(
            name='Register_Palabraclave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre Palabra Clave')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('normativas', models.ManyToManyField(blank=True, related_name='keywords', to='normas.Register_Normativa', verbose_name='Normativa')),
            ],
            options={
                'verbose_name_plural': 'Palabras Clave',
                'db_table': 'register_palabclave',
            },
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='subtipo_uso',
            field=models.ManyToManyField(blank=True, related_name='normativas', to='normas.Subtipo_Normas', verbose_name='Subtipo de uso'),
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='tipo_norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.tipo_normas', verbose_name='Tipo de Norma'),
        ),
        migrations.CreateModel(
            name='Policies_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo de Consulta', max_length=200, verbose_name='Titulo de Consulta')),
                ('message', models.TextField(help_text='Respuesta', verbose_name='Respuesta')),
                ('validity_date_start', models.DateField(help_text='Fecha Inicio', verbose_name='Fecha Inicio')),
                ('validity_date_finish', models.DateField(help_text='Fecha Fin', verbose_name='Fecha Fin')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('subtipo_uso', models.ManyToManyField(blank=True, related_name='preguntas', to='normas.Subtipo_Normas', verbose_name='Subtipo de uso')),
                ('tipo_uso', models.ManyToManyField(blank=True, related_name='preguntas', to='normas.Areas_Normas', verbose_name='Tipo de uso')),
                ('universo', models.ManyToManyField(blank=True, related_name='preguntas', to='normas.Universo_Normas', verbose_name='Universo de norma')),
            ],
            options={
                'verbose_name_plural': 'Preguntas Frecuentes',
            },
        ),
    ]
