# Generated by Django 3.2 on 2022-04-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabra_clave_normas',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='cursos.Cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='preguntas_frecuentes',
            name='title',
            field=models.CharField(help_text='Titulo de Consulta', max_length=700, verbose_name='Titulo de Consulta'),
        ),
    ]
