# Generated by Django 3.2 on 2022-03-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtipo_normas',
            name='tipo_uso',
        ),
        migrations.AddField(
            model_name='subtipo_normas',
            name='tipo_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.areas_normas', verbose_name='Tipo Uso'),
        ),
    ]
