# Generated by Django 3.2 on 2022-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='base_legal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Base Legal'),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='denominacion',
            field=models.TextField(verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='norma',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Norma'),
        ),
    ]
