# Generated by Django 3.2 on 2022-02-17 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategories_normas',
            options={'verbose_name_plural': '2.Normas - Subtipo De Normativa'},
        ),
        migrations.AlterModelOptions(
            name='subnormativa',
            options={'verbose_name_plural': '5.Normas-Normativa'},
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='es_foro',
            field=models.BooleanField(default=False, verbose_name='Es un foro'),
        ),
        migrations.AlterField(
            model_name='register_normativa',
            name='tipo_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normas', to='normas.areas_normas', verbose_name='Tipo Uso'),
        ),
        migrations.AlterField(
            model_name='subnormativa',
            name='norma',
            field=models.CharField(max_length=200, verbose_name='Normativa'),
        ),
        migrations.AlterField(
            model_name='subnormativa',
            name='norma_sub',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='normas.subcategories_normas', verbose_name='Sub Normativa'),
        ),
    ]
