# Generated by Django 3.2 on 2022-03-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_normativa',
            name='genero',
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='universo',
            field=models.CharField(choices=[('NE', 'Normativa Edificatoria'), ('PA', 'Procedimineto Administrativo')], default='NE', max_length=150),
        ),
        migrations.AlterField(
            model_name='register_normativa',
            name='estado',
            field=models.CharField(choices=[('VI', 'Vigente'), ('NV', 'No vigente'), ('DP', 'Derogado Parcialmente')], default='VI', max_length=150),
        ),
    ]
