# Generated by Django 3.2 on 2022-01-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnormativa',
            name='norma',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='normas.subcategories_normas', verbose_name='Normativa'),
        ),
    ]
