# Generated by Django 3.2 on 2022-03-29 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas_normas',
            name='register_date_time',
        ),
        migrations.RemoveField(
            model_name='register_normativa',
            name='es_foro',
        ),
        migrations.RemoveField(
            model_name='register_normativa',
            name='es_vigente',
        ),
        migrations.RemoveField(
            model_name='register_normativa',
            name='tipo_uso',
        ),
        migrations.RemoveField(
            model_name='subcategories_normas',
            name='register_date_time',
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='articulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Articulo'),
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='estado',
            field=models.CharField(choices=[('VI', 'Vigente'), ('NV', 'No vigente'), ('DP', 'Derogado Parcialmente')], default='VI', max_length=150),
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='universo',
            field=models.CharField(choices=[('NE', 'Normativa Edificatoria'), ('PA', 'Procedimiento Administrativo')], default='NE', max_length=150),
        ),
        migrations.CreateModel(
            name='Subtipo_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de subtipo')),
                ('order', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('tipo_uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.areas_normas', verbose_name='Tipo Uso')),
            ],
            options={
                'verbose_name_plural': 'Subtipo de Uso',
            },
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='subtipo_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.subtipo_normas', verbose_name='Subtipo de uso'),
        ),
    ]
