# Generated by Django 3.2 on 2022-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies_usage',
            name='subtipo_uso',
            field=models.ManyToManyField(blank=True, related_name='preguntas', to='normas.Subtipo_Normas', verbose_name='Subtipo de uso'),
        ),
        migrations.AddField(
            model_name='policies_usage',
            name='universo',
            field=models.ManyToManyField(blank=True, related_name='preguntas', to='normas.Universo_Normas', verbose_name='Universo de norma'),
        ),
    ]
