# Generated by Django 3.2 on 2022-03-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_auto_20220322_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_normativa',
            name='es_foro',
        ),
    ]
