# Generated by Django 3.2 on 2022-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20220427_0915'),
        ('normas', '0002_auto_20220426_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra_clave_normas',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='cursos.Curso', verbose_name='Curso'),
        ),
    ]
