# Generated by Django 3.2 on 2022-02-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_auto_20220217_1828'),
        ('normas', '0002_auto_20220217_2143'),
    ]

    operations = [
    ]
