# Generated by Django 3.2 on 2022-04-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_alter_register_normativa_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_normas',
            name='universo',
        ),
        migrations.AddField(
            model_name='tipo_normas',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Grupo_Tipo_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Grupo de tipo de norma')),
                ('icono', models.FileField(null=True, upload_to='iconos_grupo_normativa', verbose_name='Icono del grupo')),
                ('order', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('universo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.universo_normas', verbose_name='Universo Norma')),
            ],
        ),
        migrations.AddField(
            model_name='tipo_normas',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.grupo_tipo_normas', verbose_name='Grupo Norma'),
        ),
    ]
