# Generated by Django 3.2 on 2022-03-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_policies_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies_usage',
            name='normativas',
            field=models.ManyToManyField(blank=True, related_name='preguntas', to='normas.Register_Normativa', verbose_name='Normativa'),
        ),
        migrations.AlterField(
            model_name='register_palabraclave',
            name='normativas',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='normas.Register_Normativa', verbose_name='Normativa'),
        ),
    ]
