# Generated by Django 3.2 on 2022-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_alter_register_normativa_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_normativa',
            name='fecha_publi',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Publicacion'),
        ),
    ]
