# Generated by Django 3.2 on 2022-01-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_alter_subnormativa_norma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnormativa',
            name='norma',
            field=models.CharField(max_length=200, verbose_name='Normativa'),
        ),
        migrations.AlterField(
            model_name='subnormativa',
            name='norma_sub',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='normas.subcategories_normas', verbose_name='Sub Normativa'),
        ),
    ]
