# Generated by Django 3.2 on 2022-02-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_merge_0002_auto_20220217_1828_0002_auto_20220217_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_normativa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='register_normativa',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
    ]
