# Generated by Django 3.2 on 2022-02-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_auto_20220127_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategories_normas',
            options={'verbose_name_plural': '2.Normas - Subtipo De Normativa'},
        ),
        migrations.AlterModelOptions(
            name='subnormativa',
            options={'verbose_name_plural': '5.Normas-Normativa'},
        ),
    ]
