# Generated by Django 3.2 on 2022-02-17 12:05

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_auto_20220127_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategories_normas',
            options={'verbose_name_plural': '2.Normas - Subtipo De Normativa'},
        ),
        migrations.AlterModelOptions(
            name='subnormativa',
            options={'verbose_name_plural': '5.Normas-Normativa'},
        ),
        migrations.AlterField(
            model_name='register_normativa',
            name='tipo_uso',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='normas.areas_normas', verbose_name='Tipo Uso'),
        ),
    ]
