# Generated by Django 4.0.2 on 2022-04-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_alter_palabra_clave_normas_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas_frecuentes',
            name='tipo_norma',
            field=models.ManyToManyField(blank=True, related_name='tipos_norma', to='normas.Tipo_Normas', verbose_name='Tipo de norma'),
        ),
    ]
