# Generated by Django 3.2 on 2022-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_alter_normativa_denominacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_normas',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
