# Generated by Django 3.2 on 2022-04-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_auto_20220411_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo_tipo_normas',
            options={'verbose_name_plural': 'Grupo de Tipo de Norma'},
        ),
        migrations.AlterField(
            model_name='grupo_tipo_normas',
            name='icono',
            field=models.FileField(blank=True, null=True, upload_to='iconos_grupo_normativa', verbose_name='Icono del grupo'),
        ),
        migrations.AlterField(
            model_name='tipo_normas',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
    ]
