# Generated by Django 3.2 on 2022-04-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_alter_register_normativa_fecha_publi'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas_normas',
            name='universo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.universo_normas', verbose_name='Universo Norma'),
        ),
        migrations.AlterField(
            model_name='register_normativa',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Document_normativa', verbose_name='Documentos'),
        ),
    ]
