# Generated by Django 3.2 on 2022-02-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_auto_20220221_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_palabraclave',
            name='normativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normativa', to='normas.register_normativa', verbose_name='Normativa'),
        ),
    ]
