# Generated by Django 3.2 on 2022-03-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_auto_20220307_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies_usage',
            name='normativas',
        ),
        migrations.AddField(
            model_name='policies_usage',
            name='tipo_uso',
            field=models.ManyToManyField(blank=True, related_name='preguntas', to='normas.Areas_Normas', verbose_name='Tipo de uso'),
        ),
    ]
