# Generated by Django 3.2 on 2022-02-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0004_auto_20220221_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories_normas',
            name='order',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
