# Generated by Django 3.2 on 2022-02-21 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0004_alter_register_palabraclave_normativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_normativa',
            name='tipo_norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_norma', to='normas.subcategories_normas', verbose_name='Tipo de Norma'),
        ),
    ]
