# Generated by Django 3.2 on 2022-02-17 13:23

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0004_auto_20220217_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_normativa',
            name='tipo_uso',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='normas', to='normas.areas_normas', verbose_name='Tipo Uso'),
        ),
    ]
