# Generated by Django 3.2 on 2022-03-29 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del foro')),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name_plural': 'Foro',
            },
        ),
        migrations.CreateModel(
            name='Comentario_Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200, verbose_name='Comentario')),
                ('likes', models.PositiveSmallIntegerField(default=0, help_text='Likes', verbose_name='Likes')),
                ('dislikes', models.PositiveSmallIntegerField(default=0, help_text='Dislikes', verbose_name='Dislikes')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('foro', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.foro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
