# Generated by Django 3.2 on 2022-03-22 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coments_foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coments', models.CharField(help_text='comentario', max_length=200, verbose_name='comentario')),
                ('likes', models.PositiveSmallIntegerField(default=0, help_text='Likes', verbose_name='Likes')),
                ('dislikes', models.PositiveSmallIntegerField(default=0, help_text='Dislikes', verbose_name='Dislikes')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('tema', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='normas.register_normativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
