# Generated by Django 3.2 on 2022-04-29 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import foro.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario_foro',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AddField(
            model_name='comentario_foro',
            name='file_four',
            field=models.FileField(blank=True, null=True, upload_to='comentario_foro', verbose_name='Archivo 4'),
        ),
        migrations.AddField(
            model_name='comentario_foro',
            name='file_one',
            field=models.FileField(blank=True, null=True, upload_to='comentario_foro', validators=[foro.validators.validate_file_size], verbose_name='Archivo 1'),
        ),
        migrations.AddField(
            model_name='comentario_foro',
            name='file_three',
            field=models.FileField(blank=True, null=True, upload_to='comentario_foro', verbose_name='Archivo 3'),
        ),
        migrations.AddField(
            model_name='comentario_foro',
            name='file_two',
            field=models.FileField(blank=True, null=True, upload_to='comentario_foro', verbose_name='Archivo 2'),
        ),
        migrations.AlterField(
            model_name='comentario_foro',
            name='comentario',
            field=models.CharField(max_length=150, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario_foro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coment', to=settings.AUTH_USER_MODEL),
        ),
    ]
