# Generated by Django 3.2 on 2022-05-01 17:07

from django.db import migrations, models
import foro.validators


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20220429_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario_foro',
            name='file_four',
            field=models.FileField(blank=True, null=True, upload_to='comentario_foro', validators=[foro.validators.validate_file_size], verbose_name='Archivo 4'),
        ),
        migrations.AlterField(
            model_name='comentario_foro',
            name='file_three',
            field=models.FileField(blank=True, null=True, upload_to='comentario_foro', validators=[foro.validators.validate_file_size], verbose_name='Archivo 3'),
        ),
        migrations.AlterField(
            model_name='comentario_foro',
            name='file_two',
            field=models.FileField(blank=True, null=True, upload_to='comentario_foro', validators=[foro.validators.validate_file_size], verbose_name='Archivo 2'),
        ),
    ]
