# Generated by Django 3.2 on 2022-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_alter_comentario_foro_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario_foro',
            name='comentario',
            field=models.CharField(max_length=150, verbose_name='Comentario'),
        ),
    ]
