# Generated by Django 3.2 on 2022-04-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_alter_comentario_foro_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario_foro',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Comentarios'},
        ),
    ]
