# Generated by Django 3.2 on 2022-04-29 13:22

from django.db import migrations, models
import foro.validators


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_alter_comentario_foro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario_foro',
            name='file_one',
            field=models.FileField(blank=True, null=True, upload_to='comentario_foro', validators=[foro.validators.validate_file_size], verbose_name='Archivo 1'),
        ),
    ]
