# Generated by Django 3.2 on 2022-03-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_auto_20220303_0856'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='suscribcion_foro',
            field=models.ManyToManyField(related_name='suscribcion_foro', to='normas.Register_Normativa'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='Correo Electrónico', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, choices=[('A', 'ARQUITECTO'), ('I', 'INGENIERO'), ('O', 'OTRO')], help_text='Profesión', max_length=1, verbose_name='Profesión'),
        ),
        migrations.DeleteModel(
            name='Policies_usage',
        ),
    ]
