# Generated by Django 3.2 on 2022-03-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsagePolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Politicas de uso')),
                ('member_policies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_policies', to='apps.member')),
            ],
        ),
    ]
