# Generated by Django 3.2 on 2022-03-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20220323_0953'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='suscripcion_foro',
            field=models.ManyToManyField(blank=True, related_name='suscripcion_foro', to='foro.Foro'),
        ),
    ]
