# Generated by Django 3.2 on 2022-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_policies_usage'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policies_usage',
        ),
        migrations.AlterField(
            model_name='member',
            name='suscripcion_foro',
            field=models.ManyToManyField(null=True, related_name='suscripcion_foro', to='normas.Register_Normativa'),
        ),
    ]
