# Generated by Django 3.2 on 2022-03-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_auto_20220302_0823'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies_usage',
            name='norma_name',
        ),
        migrations.RemoveField(
            model_name='policies_usage',
            name='platform',
        ),
        migrations.AddField(
            model_name='policies_usage',
            name='norma',
            field=models.ManyToManyField(related_name='preguntas_frecuentes', to='normas.Register_Normativa'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='Correo Electrónico', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='policies_usage',
            name='validity_date_finish',
            field=models.DateField(help_text='Fecha Fin', verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='policies_usage',
            name='validity_date_start',
            field=models.DateField(help_text='Fecha Inicio', verbose_name='Fecha Inicio'),
        ),
    ]
