# Generated by Django 3.2 on 2022-03-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='person_type',
            field=models.CharField(blank=True, choices=[('N', 'NATURAL'), ('J', 'JURÍDICA')], default='N', help_text='Tipo de Persona', max_length=1, verbose_name='Tipo de Persona'),
        ),
    ]
