# Generated by Django 3.2 on 2022-03-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_usagepolicies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagepolicies',
            name='member_policies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_policies', to='apps.member'),
        ),
    ]
