# Generated by Django 3.2 on 2022-03-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_auto_20220307_2025'),
        ('apps', '0002_auto_20220307_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='suscripcion_foro',
            field=models.ManyToManyField(blank=True, related_name='suscripcion_foro', to='normas.Register_Normativa'),
        ),
    ]
