# Generated by Django 3.2 on 2022-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20220502_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tuition',
            field=models.CharField(blank=True, help_text='Colegiatura', max_length=16, null=True, verbose_name='Colegiatura'),
        ),
    ]
