# Generated by Django 3.2 on 2022-02-28 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0002_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='has_tutition',
            field=models.BooleanField(default=False, verbose_name='¿Es colegiado?'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='¿Esta habilitado?'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_membership', to='membership.membership'),
        ),
        migrations.AddField(
            model_name='member',
            name='penalty_fee',
            field=models.BooleanField(default=False, verbose_name='¿Tiene multas?'),
        ),
        migrations.AddField(
            model_name='member',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, choices=[('A', 'ARQUITECTO'), ('I', 'INGENIERO'), ('O', 'OTRO')], help_text='Profesión', max_length=1, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
