# Generated by Django 3.2 on 2022-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_member_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_payment',
            name='identity',
            field=models.CharField(blank=True, help_text='DNI o RUC', max_length=16, verbose_name='Documento de Identidad'),
        ),
    ]
