# Generated by Django 3.2 on 2022-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_usagepolicies_member_policies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagepolicies',
            name='member_policies',
        ),
        migrations.AddField(
            model_name='usagepolicies',
            name='member_policies',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_policies', to='apps.Member'),
        ),
    ]
