# Generated by Django 3.2 on 2022-03-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20220310_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagepolicies',
            name='member_policies',
            field=models.ManyToManyField(blank=True, related_name='member_policies', to='apps.Member'),
        ),
    ]
