# Generated by Django 3.2 on 2022-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_usagepolicies_member_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagepolicies',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
