# Generated by Django 3.2 on 2022-03-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_usagepolicies_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagepolicies',
            options={'verbose_name': 'Politcas de Usos', 'verbose_name_plural': 'Politcas de Usos'},
        ),
        migrations.AddField(
            model_name='usagepolicies',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
