# Generated by Django 3.2 on 2022-03-10 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20220310_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagepolicies',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='usagepolicies',
            name='register_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de Registro', verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagepolicies',
            name='validity_date_finish',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha Fin', verbose_name='Fecha Fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagepolicies',
            name='validity_date_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha Inicio', verbose_name='Fecha Inicio'),
            preserve_default=False,
        ),
    ]
