# Generated by Django 3.2 on 2022-03-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20220310_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagepolicies',
            options={'verbose_name': 'Politicas de Uso', 'verbose_name_plural': 'Politicas de Uso'},
        ),
    ]
