# Generated by Django 3.2 on 2022-03-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_usagepolicies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(help_text='Nombres O Razón Social', max_length=50, verbose_name='Nombres')),
                ('first_surname', models.CharField(blank=True, help_text='Apellido Paterno', max_length=50, verbose_name='Apellido Paterno')),
                ('second_surname', models.CharField(blank=True, help_text='Apellido Materno', max_length=50, verbose_name='Apellido Materno')),
                ('email', models.EmailField(blank=True, help_text='Correo Electrónico', max_length=50, null=True, verbose_name='Email')),
                ('paid', models.BooleanField(default=False)),
                ('braintree_id', models.CharField(blank=True, max_length=150)),
                ('pay_method', models.CharField(blank=True, choices=[('E', 'VISA'), ('V', 'EFECTIVO')], help_text='Metodo de Pago', max_length=1, verbose_name='Metodo de Pago')),
                ('pay_import', models.DecimalField(decimal_places=2, help_text='Importe Pagado', max_digits=10, verbose_name='Importe Pagado')),
                ('validity_date_start', models.DateField(help_text='Fecha Inicio membresia', verbose_name='Fecha Inicio membresia')),
                ('validity_date_finish', models.DateField(help_text='Fecha Fin membresia', verbose_name='Fecha Fin membresia')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de Modificacion', verbose_name='Fecha de Modificacion')),
                ('id_plan', models.OneToOneField(blank=True, help_text='Plan Suscrito', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.plan', verbose_name='Plan de Suscripcion')),
                ('member', models.ForeignKey(blank=True, help_text='Miembros', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='apps.member', verbose_name='Miembros')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Pagos',
            },
        ),
        migrations.DeleteModel(
            name='Control_payment',
        ),
    ]
