# Generated by Django 3.2 on 2022-03-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_order_payment_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_payment',
            old_name='braintree_id',
            new_name='niubiz_id',
        ),
    ]
