# Generated by Django 3.2 on 2022-03-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_rename_braintree_id_order_payment_niubiz_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_payment',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Ordenes de Pagos'},
        ),
        migrations.AlterField(
            model_name='order_payment',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de Modificacion del Registro', verbose_name='Fecha de Modificacion del Registro'),
        ),
    ]
