# Generated by Django 3.2 on 2022-03-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20220316_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='identity',
            field=models.CharField(blank=True, help_text='DNI o RUC', max_length=11, verbose_name='Documento de Identidad'),
        ),
    ]
