# Generated by Django 3.2 on 2022-03-20 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_order_payment_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_payment',
            options={'ordering': ['-created'], 'verbose_name': 'Ordenes de Pagos', 'verbose_name_plural': 'Ordenes de Pagos'},
        ),
        migrations.RemoveField(
            model_name='order_payment',
            name='id_plan',
        ),
        migrations.CreateModel(
            name='NiubizTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoreTransactionUUID', models.CharField(blank=True, max_length=100, verbose_name='Identificador de la transaccion niubiz')),
                ('channel', models.CharField(blank=True, max_length=100, verbose_name='Canal de registro')),
                ('signature', models.CharField(blank=True, max_length=100, verbose_name='Codigo niubiz')),
                ('tokenId', models.CharField(blank=True, max_length=100, verbose_name='Token formulario niubiz')),
                ('purchaseNumber', models.CharField(blank=True, max_length=100, verbose_name='Numero de pedido')),
                ('amount', models.CharField(blank=True, max_length=100, verbose_name='Importe de la transaccion')),
                ('installment', models.CharField(blank=True, max_length=100, verbose_name='Numero de cuotas')),
                ('currency', models.CharField(blank=True, max_length=100, verbose_name='Moneda')),
                ('authorizedAmount', models.CharField(blank=True, max_length=100, verbose_name='Importe confirmado')),
                ('authorizationCode', models.CharField(blank=True, max_length=100, verbose_name='Codigo de autorización')),
                ('traceNumber', models.CharField(blank=True, max_length=100, verbose_name='Identificador de la orden de transaccion')),
                ('transactionDate', models.DateField(blank=True, verbose_name='Fecha de la transacion')),
                ('card', models.CharField(blank=True, max_length=16, verbose_name='Numero de tarjeta')),
                ('action_description', models.CharField(blank=True, max_length=100, verbose_name='Descripcion de la transaccion')),
                ('transaction_date', models.CharField(blank=True, max_length=100, verbose_name='Fecha de la transaccion')),
                ('brand', models.CharField(blank=True, max_length=15, verbose_name='Nombre de la tarjeta')),
                ('order_pyment', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='niubiz_transaction', to='apps.order_payment')),
            ],
            options={
                'verbose_name': 'Transaccion Niubiz',
                'verbose_name_plural': 'Transaccion Niubiz',
            },
        ),
    ]
