# Generated by Django 3.2 on 2022-03-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20220320_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niubiztransaction',
            name='transactionDate',
        ),
    ]
