# Generated by Django 3.2 on 2022-03-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_remove_niubiztransaction_transactiondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niubiztransaction',
            name='transaction_date',
        ),
    ]
