# Generated by Django 3.2 on 2022-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_alter_niubiztransaction_order_pyment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_payment',
            name='validity_date_finish',
            field=models.DateTimeField(help_text='Fecha Fin membresia', verbose_name='Fecha Fin membresia'),
        ),
        migrations.AlterField(
            model_name='order_payment',
            name='validity_date_start',
            field=models.DateTimeField(help_text='Fecha Inicio membresia', verbose_name='Fecha Inicio membresia'),
        ),
    ]
