# Generated by Django 3.2 on 2022-03-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20220323_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='¿Es cliente?'),
        ),
    ]
