# Generated by Django 3.2 on 2022-03-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
        ('apps', '0020_member_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='suscripcion_foro',
            field=models.ManyToManyField(blank=True, related_name='suscripcion_foro', to='foro.Foro'),
        ),
    ]
